package com.backandwhite.domain.valueobject;

public enum EmailTrigger {
    ORDER_CONFIRMED, ORDER_SHIPPED, ORDER_DELIVERED, RETURN_APPROVED, RETURN_REFUNDED, WELCOME, PASSWORD_RESET, NEWSLETTER, GIFT_CARD, CUSTOM
}
